apiVersion: v1
kind: Service
metadata:
  name: ames-panel-registration-ui
  namespace: ames-dev
  labels:
    app: ames-panel-registration-ui
    app.kubernetes.io/part-of: ames
spec:
  type: NodePort
  selector:
    app: ames-panel-registration-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30101
